closes #11 find and set up test framework
PUM04/pum-04 pull request #17
Opened 2023-03-06 10:41 UTC by rajtarn

2023-03-26 16:57 UTC, rajtarn commented
https://github.com/PUM04/pum-04/pull/28#pullrequestreview-1358009954

2023-04-05 06:28 UTC, AntonOstman requested changes
Does not look like this was merged with main before the PR was created. Otherwise I don't see any issues, Nice work!

2023-04-05 06:58 UTC, AntonOstman approved these changes
Nice!

2023-04-06 08:35 UTC, ViktorAndersson99 approved these changes
Nice work!

2023-04-06 08:39 UTC, ELEMENTLHERO commented on src/components/Example.tsx
Varför tar ni bort WASM Calculator? Är det för den är irrelevant och WASM verkar funka nu? Inget fel bara undrade

2023-04-06 08:51 UTC, merged