22 feature dropdown menu for seeing sites or metrics
PUM04/pum-04 pull request #54
Opened 2023-04-11 13:20 UTC by Grukank

Bra att veta: Lintingen ogillar placeringen av import Box i App.tsx, men den behöver vara just där av någon anledning.

2023-04-11 14:32 UTC, AntonOstman commented on src/App.tsx
> +// Linting kommer klaga på att Box ligger här, men ligger den högre upp funkar inte webbsidan
for some reason 
![image](https://user-images.githubusercontent.com/95719901/231196022-ddb45ab6-b3f4-4cbd-b3dc-7403c9f6bf79.png)
this function is undefined when box is imported before Example. Not sure if it is worth investigating further

2023-04-11 15:11 UTC, rajtarn requested changes
Looks good! Nice tests!

Some conflicts with main needs to be resolved, and the import problem will hopefully be resolved with that as well

2023-04-12 15:13 UTC, AlgotE commented on src/App.tsx
> +      <p>Hejsan</p>
Conflicts with main has been resolver

2023-04-12 16:07 UTC, CajsaWargren approved these changes
it works, good job!

2023-04-12 16:09 UTC, adsamu approved these changes
looks good!

2023-04-12 16:11 UTC, rajtarn approved these changes
Good job!

2023-04-12 16:11 UTC, rajtarn commented on src/App.css
Nice catch!

We could also call `.trim()` on the css variable to remove any padding.

2023-04-12 16:39 UTC, merged